### PR TITLE
cache: Fix indexing to index the cache, not itself

### PR DESCRIPTION
**Pull request by the-maldridge**
Well that bug should have been spotted earlier.  I was writing the offsets of the index file, not the offsets of the actual cache.  This PR fixes that and writes the offsets of the correct file into the index and makes it perform as expected.

### CODE REVIEW

**Review by MiLk — COMMENTED** [review]
Could you manage to reproduce the issues with `getent` in https://github.com/MiLk/nsscache-go/blob/master/nsscache_test.go ?
I would feel more comfortable if we could catch any regression on this in the future.

**Comment by the-maldridge** [comment]
Generally speaking no, as for the size cache its practical to use in the unit tests libnss-cache can fall back to a linear search.  There is a test for the index generation, but foolishly I used the code to generate its own tests results initially rather than calculating a set of known correct values for testing (strictly speaking I think it can always try to fall back, but for many use cases this fallback can cause noticable stuttering in the calling process).

I will import this patch into a downstream application and check it, then post back here with examples of what was wrong and how this fixes it.

**Review by MiLk — APPROVED** [review]

**Comment by MiLk** [comment]
Ok, I leave the PR open for now.
Please share your findings whenever you can.

**Comment by the-maldridge** [comment]
Will do, I am verifying the problem now on a larger dataset and then I will produce a set of diffs that is small enough to paste here.

**Comment by the-maldridge** [comment]
Alright, I was able to verify the behavior with a test and reproduce it with a smaller dataset locally.  Here's what was happening with the bad version:

```
$ ../nsscache/nsscache.bad --out t --min-gid 0
$ cat t/group.cache
group1:x:1:
dgroup1:x:2000:dummy1
group2:x:2:
$ cat t/group.cache.ixname
dgroup100000000
group100000023
group200000036
```

Note that even though dgroup1 appears second in the cache file, the offset for it in the index is written as the 0th byte, i.e. top of file.  This is because the index was initially computing the right length for each record, but using the order of the index (sorted) rather than the order of the cache (unspecified).

Here's what it should look like:

```
$ ../nsscache/nsscache.good --out t --min-gid 0
$ cat t/group.cache
group1:x:1:
dgroup1:x:2000:dummy1
group2:x:2:
$ cat t/group.cache.ixname
dgroup100000013
group100000000
group200000036
```

Note that while the order of the cache file and the order of the keys in the index file are the same, the offset in the index file now points to the seek() position for the specified record.

Strictly speaking I probably should have noticed this when I was writing the test case that my offsets were all in ascending order, which shouldn't have been possible since I deliberately unordered the test data to ensure this case would be tested.  Further regressions should be caught by the existing test case which now has correct data that I have verified by hand and using the algorithm I originally ported from (as shown in #8).

**Comment by the-maldridge** [comment]
Wait something's still not right.

**Comment by the-maldridge** [comment]
Alright, somewhere there's an error in my math that I'm not confident in.  I am going to review this with pen and paper tomorrow and see if I can get a second set of eyes as well on it.

**Comment by the-maldridge** [comment]
A day later and I have more questions than answers.  I've made some progress though, most importantly porting the mostly-fixed-length record format from Python to Go.  The problem now is that there's some disagreement about the offset value that's necessary for the index to be used.  In python the number of bytes written is always padded by 1, but this appears to cause a stacked error in the offset in the file, so I have omitted this from the function here.  I have made a post to nsscache-discuss to try and get more information on this, but have not received a reply yet.

I've also added the index files to the docker based test which should have been done in the original index PR.

Since the bogus indexes don't actually appear to be breaking anything, I'd like to hold off merging this until a reply comes through on the mailing list to get more information about why this is working with bad cache indexes, and what the correct index format should be.

**Comment by the-maldridge** [comment]
Let it be known that many yaks were shaved in the resolution of this bug. TL;DR: the +1 offset is bogus and generates invalid indexes, my original hunch was right and it should just be the sum of the line length of all previous lines.

The longer explanation:
---

To properly troubleshoot this we ideally want to be able to debug libnss_cache.so itself while its reading the files to know if the cache index is working.  This is some of the least readable C I've seen in a long time and this is compounded by the tests and DEBUG macro both being broken at master.  I have a local branch that fixes the debug macro and I'll follow that up with a PR to libnss-cache that fixes the tests once nsscache-go has a stable release in order to try and have the loop closed on tests.

Building from a branch I had a version that would work to determine what was going on inside libnss-cache, and testing could proceed.  For posterity, I built a debuggable container using this dockerfile:

```
FROM debian:stable-slim

WORKDIR /tmp/nsscache

RUN apt-get update \
 && apt-get install -y git make gcc \
 && rm -rf /var/lib/apt/lists/* \
 && git clone -b working-tests git://github.com/the-maldridge/libnss-cache.git .

RUN make CFLAGS="-DDEBUG -fPIC" \
 && make install

COPY nsswitch.conf /etc/nsswitch.conf

WORKDIR /
CMD ["getent"]
```

With that done, I could try both versions of the cache index to determine empirically which one actually worked.  Here's the version where 1 is added to the offset for each entry:

```
$ nsscache.bad --out t/
$ xxd -c 13 < t/passwd.cache.ixname 
00000000: 6475 6d6d 7931 0030 0000 0000 0a  dummy1.0.....
0000000d: 656e 7469 7479 3100 3431 0000 0a  entity1.41...
0000001a: 656e 7469 7479 3130 0032 3536 0a  entity10.256.
00000027: 656e 7469 7479 3200 3338 3700 0a  entity2.387..
00000034: 656e 7469 7479 3300 3834 0000 0a  entity3.84...
00000041: 656e 7469 7479 3400 3132 3700 0a  entity4.127..
0000004e: 656e 7469 7479 3500 3433 3000 0a  entity5.430..
0000005b: 656e 7469 7479 3600 3137 3000 0a  entity6.170..
00000068: 656e 7469 7479 3700 3231 3300 0a  entity7.213..
00000075: 656e 7469 7479 3800 3330 3100 0a  entity8.301..
00000082: 656e 7469 7479 3900 3334 3400 0a  entity9.344..
$ docker run --rm -it -v $PWD/t/passwd.cache:/etc/passwd.cache -v $PWD/t/passwd.cache.ixname:/etc/passwd.cache.ixname -v $PWD/t/group.cache:/etc/group.cache -v $PWD/t/shadow.cache:/etc/shadow.cache nsscache-go:debuggable getent passwd entity1
Binary search for user entity1
Failed match at name ntity1
Binary search failed, falling back to full linear search
Opening /etc/passwd.cache
Returning user 2000:dummy1
Returning user 2001:entity1
Closing passwd.cache
entity1:x:2001:2000::/tmp/entity1:/bin/sh
failed to resize tty, using default size
```

As would be expected with the corrupt index, the fseek() lands at the wrong offset and the name match fails.  At this point, libnss-cache falls back to a linear search through the library rather actually bailing out (I believe this is incorrect behavior, and may represent a security problem, but that's a discussion for another time).  This is, incidentally, why the tests in nsscache-go still pass even with corrupt indexes.  If we remove the `+ 1` and write indexes with the correct values, here is the output:

```
$ nsscache.good --out t
$ xxd -c 13 < t/passwd.cache.ixname 
00000000: 6475 6d6d 7931 0032 3936 0000 0a  dummy1.296...
0000000d: 656e 7469 7479 3100 3333 3600 0a  entity1.336..
0000001a: 656e 7469 7479 3130 0030 0000 0a  entity10.0...
00000027: 656e 7469 7479 3200 3434 0000 0a  entity2.44...
00000034: 656e 7469 7479 3300 3836 0000 0a  entity3.86...
00000041: 656e 7469 7479 3400 3132 3800 0a  entity4.128..
0000004e: 656e 7469 7479 3500 3337 3800 0a  entity5.378..
0000005b: 656e 7469 7479 3600 3432 3000 0a  entity6.420..
00000068: 656e 7469 7479 3700 3137 3000 0a  entity7.170..
00000075: 656e 7469 7479 3800 3231 3200 0a  entity8.212..
00000082: 656e 7469 7479 3900 3235 3400 0a  entity9.254..
$ docker run --rm -it -v $PWD/t/passwd.cache:/etc/passwd.cache -v $PWD/t/passwd.cache.ixname:/etc/passwd.cache.ixname -v $PWD/t/group.cache:/etc/group.cache -v $PWD/t/shadow.cache:/etc/shadow.cache nsscache-go:debuggable getent passwd entity1
Binary search for user entity1
SUCCESS: found user entity1
Closing passwd.cache
entity1:x:2001:2000::/tmp/entity1:/bin/sh
failed to resize tty, using default size
```

The binary search locates the correct index entry, which has the correct offset in it, this enables the fseek() to jump directly to the right entry, and the getpwent call can return after a single read.

The code on this branch will shortly be updated to include the patch that makes all this work, at which point I'd be very grateful if you'd merge and cut a bugfix release that includes this patch.

**Comment by the-maldridge** [comment]
Code on the branch is up to date.  Travis has a transient error on 1.12 unrelated to this patch, if you restart that build it should go green.

**Pull request merged**
